root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/app/main"
  cmd = "templ generate components && tailwindcss -i components/styles.css -o assets/styles.css -m && go build -o tmp/app/main ./cmd/app/main.go "
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false